export const MESSAGE = {

  CONGRATULATION: 'Congratulations!',
  INCORRECT_LOGIN: 'Incorrect email address and  or password.',
  TITLE_CONFIRM_LOGOUT: 'Do you want to logout?',
  TITLE_CONFIRM_DELETE_EMPLOYER: 'Do you want to delete this employer?',
  TITLE_CONFIRM_DELETE_COUPON: 'Are you want sure to delete the coupon?',
  TITLE_CONFIRM_DEACTIVE_COUPON: 'Are you sure you want to deactivate this coupon before it is set to expire?',
  TITLE_CONFIRM_DEACTIVE_EMPLOYER: 'Do you want to deactivate this employer?',
  TITLE_CONFIRM_ACTIVATE_EMPLOYER: 'Do you want to activate this employer?',
  TITLE_CONFIRM_DEACTIVE_JOBPOSTING: 'Do you want to deactivate this job posting?',
  TITLE_CONFIRM_ACTIVATE_JOBPOSTING: 'Do you want to activate this job posting?',
  TITLE_CONFIRM_DELETE_JOBSEEKER: 'Do you want to delete this Job Seeker?',
  TITLE_CONFIRM_DEACTIVE_JOBSEEKER: 'Do you want to deactivate this Job Seeker?',
  TITLE_CONFIRM_ACTIVATE_JOBSEEKER: 'Do you want to activate this Job Seeker?',
  BTN_OK_TEXT: 'OK',
  BTN_YES_TEXT: 'Yes',
  BTN_NO_TEXT: 'No',
  UNAUTHRRIZED: 'unauthorized',
  BTN_CANCEL_TEXT: 'Cancel',
  BTN_DELETE_TEXT: 'Delete',
  BTN_DEACTIVATE_TEXT: 'Deactivate',
  ACCESS_DENIED: 'Session Expired, Please re-login.',
  RESET_PASSWORD_SUCCESSFULY: 'Your password has been set successfully.',
  ERROR: 'Error message.',
  NOTE_SELECT_AVATAR_JOB_SEEKER: 'Please select a photo with size of 800 x 800 pixels for better quality.',
  NOTE_SELECT_AVATAR_EMPLOYER: 'Please select a photo with size of 1400 x 800 pixels for better quality.',
  UPDATE_EMPLOYER_SUCCESS: 'Your employer has been updated successfully.',
  UPDATE_JOBSEEKER_SUCCESS: 'Your Job Seeker has been updated successfully.',
  UPDATE_JOB_POSTING_SUCCESS: 'Your Job Posting has been updated successfully.',
  UPDATE_JOB_CRAWLS_SUCCESS: 'Your Job has been updated successfully.',
  UPDATE_COUPON_SUCCESS: 'Your coupon has been updated successfully.',
  CREATE_COUPON_SUCCESS: 'Your coupon has been created successfully.',
  REACTIVATE_COUPON_SUCCESS: 'Your coupon has been reactivate expired successfully.',
  DELETE_EMPLOYER_SUCCESS: 'Employer has been deleted successfully.',
  UPDATED_BLACKLIST_SUCCESS: 'This has been updated successfully.',
  CREATE_BLACKLIST_SUCCESS: 'This has been created successfully.',
  DELETE_JOB_POSTING_SUCCESS: 'Job Postings has been deleted successfully.',
  DELETE_JOB_CRAWLING_SUCCESS: 'Job Crawlings has been deleted successfully.',
  EXLUCE_COMPANY_CRAWLING_SUCCESS: 'Company has been exclude successfully.',
  DELETE_COUPON_SUCCESS: 'Coupon has been deleted successfully.',
  DEACTIVATE_COUPON_SUCCESS: 'Coupon has been deactivate successfully.',
  RESTORE_JOB_POSTING_SUCCESS: 'Job Postings has been restore successfully.',
  DELETE_JOBSEEKER_SUCCESS: 'Job seeker has been deleted successfully.',
  TITLE_CONFIRM_DELETE_JOB_POSTINGS: 'Do you want to delete these job posts?',
  TITLE_CONFIRM_DELETE_JOB_CRAWLINGS: 'Do you want to delete these job crawls?',
  TITLE_CONFIRM_SHOW_JOB_CRAWLINGS: 'Do you want to show scrape disclaimer text?',
  TITLE_CONFIRM_HIDE_JOB_CRAWLINGS: 'Do you want to hide scrape disclaimer text?',
  TITLE_CONFIRM_EXCLUDE_COMPANY_CRAWLINGS: 'Do you want to exluce these company?',
  TITLE_CONFIRM_DELETE_BLACKLIST: 'Do you want to delete?',
  TITLE_CONFIRM_RESTORE_JOB_POSTINGS: 'Do you want to restore this job postings?',
  TITLE_CONFIRM_RESTORE_EMPLOYERS: 'Do you want to restore this employer?',
  TITLE_CONFIRM_REASSIGN_EMPLOYERS: 'Do you want to re-assign this employer?',
  TITLE_CONFIRM_RESTORE_JOBSEEKERS: 'Do you want to restore this jobseeker?',
  SUM_POINT_TOO_MAX: 'Total weighting of assessment scores must equal 100%.',
  POINT_EXIST_ZERO: 'The weighting value of 1 assessment must be greater than 0.',
  UPDATE_BILLING_SETTING_SUCCESS: 'Your settings have been updated.',
  TITLE_DEACTIVE_ADMIN: 'Do you want to deactivate this admin?',
  INVITE_ADMIN_SUCCESSFULLY: 'Invite Admin successfully.',
  UPDATE_ADMIN_INFO_SUCCESSFULLY: 'Update Admin info successfully.',
  DEACTIVE_ADMIN_SUCCESSFULLY: 'Deactivate Admin successfully.',
  EMAIL_EXIST: 'Email is Exist.',
  DELETE_BLACKLIST_USER: 'Deleted successfully.',
  ACTIVE_JOBS_SUCCESS: 'Activate Jobs successfully.',
  REASSIGN_MEMBER_SUCCESS: 'Re-assign successfully.',

  TITLE_CONFIRM_CLAIMED_CRAWLINGS: 'Are you sure this company account is claimed?',
  TITLE_CONFIRM_UNCLAIMED_CRAWLINGS: 'Are you sure this company account is unclaimed?',
  CONFIRM_DELETE_EMPLOYER_PHOTO: 'Are your sure you want to remove this image?',

  WARNING_SIZE_UPLOAD_FILE: 'File size exceeds 5 MB limit.',
  WARNING_FILE_NOT_SUPPORT: 'This file type is not supported. Please select another one.',
  WARNING_SIZE_UPLOAD_IMAGE: 'Image size must be at least 15 KB.',
}

